var config      = require('../config'),
    gutil       = require('gulp-util'),
    gulp        = require('gulp'),
    gulpif      = require('gulp-if'),
    path        = require('path'),
    connect     = require('gulp-connect'),
    concat      = require('gulp-concat'),
    rename      = require('gulp-rename'),
    concatJson2js      = require('gulp-concat-json2js'),
    sourcemaps  = require('gulp-sourcemaps'),
    ngAnnotate  = require('gulp-ng-annotate'),
    templateCache = require('gulp-angular-templatecache'),
    uglify      = require('gulp-uglify');

gulp.task('concat',['concat-app'], function(){
    // concat tmp files into one dist file:
    return gulp.src([path.join(config.TMP_JS, "vendors.js"),path.join(config.TMP_JS,"app.js")])
    //gulp.src([path.join(config.TMP_JS,"app.js")])
        //.pipe(gulpif(config.env.jsSourceMaps , sourcemaps.init()))
        .pipe(concat('app.js'))
        //.pipe(gulpif(config.env.jsUglify , ngAnnotate() )) // fix uglify mangleling - not compatible with sourceMaps
        //.pipe(gulpif(config.env.jsUglify , uglify() ))
        //.pipe(gulpif(config.env.jsSourceMaps , sourcemaps.write()))
        .pipe(gulp.dest(config.DIST_JS))


});
gulp.task('concat-templates', function(){
    // before build JS we need to regenerate template file:
    return gulp.src(path.join(config.SRC_JS,"**", "*.html")) //'./app/src/**/*.html')
        .pipe(templateCache({
            filename: 'autogeneratedModule.js',
            module:'cachedTemplates',
            //standalone: true
        }))
        .pipe(gulp.dest(path.join(config.TMP_JS)));
});
gulp.task('concat-vendors', function(){
    // concat application vendors
    return gulp.src([path.join(config.SRC_JS,"vendors.json")])
        //.pipe(gulpif(config.env.jsSourceMaps , sourcemaps.init()))
        .pipe(concatJson2js('vendors.js'))
        .pipe(gulpif(config.env.jsUglify , ngAnnotate() )) // fix uglify mangleling - not compatible with sourceMaps
        .pipe(gulpif(config.env.jsUglify , uglify() ))
        .pipe(rename({basename: 'vendors'})) //,suffix: '.min'
        //.pipe(gulpif(config.env.jsSourceMaps , sourcemaps.write()))
        .pipe(gulp.dest(config.TMP_JS))
});

// app depend of template and vendors file generation
gulp.task('concat-app', ['concat-templates', 'concat-vendors'], function(){
    // then build all js sources:
    return gulp.src([
            path.join(config.SRC_JS,"**", "main.js"),
            path.join(config.TMP_JS, "autogeneratedModule.js"),
            path.join(config.SRC_JS,"**", "*.js")])
        //.pipe(gulpif(config.env.jsSourceMaps , sourcemaps.init()))
        .pipe(concat('app.js'))
        .pipe(gulpif(config.env.jsUglify , ngAnnotate() )) // fix uglify mangleling - not compatible with sourceMaps
        .pipe(gulpif(config.env.jsUglify , uglify() ))
        //.pipe(gulpif(config.env.jsSourceMaps , sourcemaps.write()))
        .pipe(gulp.dest(config.TMP_JS))
});

